version: "3.7"

networks:
    mathmpr:
        name: mathmpr

services:
    mathmpr:
        build:
            args:
                user: mathmpr
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: mathmpr
        container_name: mathmpr-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - mathmpr

    db:
        image: mysql:8.0
        container_name: mathmpr_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: mathmpr
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: mathmpr
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - mathmpr

    nginx:
        image: nginx:1.17-alpine
        container_name: mathmpr-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
            - ./storage:/var/www/storage
            - ./storage/app/public:/var/www/html/public/storage
        networks:
            - mathmpr
